project:
  type: website

website:
  title: "Serena's DS Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/syxrg
      - icon: linkedin
        href: https://linkedin.com/serenag72
format:
  html:
    theme: cosmo
    css: styles.css



