{
  "hash": "44ffce2c1a155dcb225d56889693c2e0",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Largest Companies of USA\"\nauthor: \"Serena Gong\"\ndate: \"2024-12-04\"\ncategories: [companies, data analysis, R]\n---\n\n\n![](thumbnail.jpg)\n\nGlobal companies vary widely in revenue and growth trajectories, raising the question of what factors drive revenue growth in the business world. In this post, I analyze the **Top Companies Dataset** to explore whether the **number of employees** and **industry type** influence revenue growth using a regression model and data visualization.\n\nThe dataset includes key characteristics of the world’s largest companies, including their revenue, revenue growth, employee count, and industry type. This analysis focuses on understanding how **company size (employees)** and **industry** impact **revenue growth**.\n\n------------------------------------------------------------------------\n\n### **Data Preparation**\n\nTo begin, I loaded and cleaned the dataset for analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load libraries\nlibrary(tidyverse)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Read the dataset\ncompanies <- read_csv(\"companies.csv\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Data cleaning and transformations\ncompanies <- companies %>%\n  mutate(\n    revenue_usd_millions = parse_number(as.character(`Revenue (USD millions)`)),\n    revenue_growth = parse_number(as.character(`Revenue growth`)),\n    employees = parse_number(as.character(Employees))\n  )\n```\n:::\n\n\n------------------------------------------------------------------------\n\n### **Regression Analysis**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit a multiple regression model\nrevenue_growth_model <- lm(revenue_growth ~ employees + Industry, data = companies)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Display the summary of the regression model\nsummary(revenue_growth_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = revenue_growth ~ employees + Industry, data = companies)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-34.685  -3.026   0.000   3.706 106.840 \n\nCoefficients:\n                                              Estimate Std. Error t value\n(Intercept)                                  8.522e+00  1.447e+01   0.589\nemployees                                    7.360e-06  1.105e-05   0.666\nIndustryAgriculture cooperative             -1.320e+01  2.494e+01  -0.529\nIndustryAgriculture manufacturing            7.368e+00  2.491e+01   0.296\nIndustryAirline                              4.681e+00  1.856e+01   0.252\nIndustryApparel                              4.622e-01  2.491e+01   0.019\nIndustryAutomotive and energy                9.244e+00  2.490e+01   0.371\nIndustryAutomotive industry                  7.770e-01  2.033e+01   0.038\nIndustryBeverage                            -3.833e+00  2.034e+01  -0.188\nIndustryChemical industry                   -3.039e+01  2.493e+01  -1.219\nIndustryConglomerate                        -6.155e+00  1.858e+01  -0.331\nIndustryConglomerate and telecommunications -8.229e+00  2.490e+01  -0.331\nIndustryConsumer products manufacturing     -7.009e+00  2.490e+01  -0.281\nIndustryElectronics industry                -1.251e+01  2.490e+01  -0.502\nIndustryEnergy trading                      -2.776e+01  2.495e+01  -1.113\nIndustryFinancial                            4.715e+00  2.036e+01   0.232\nIndustryFinancial services                   4.390e+01  2.496e+01   1.758\nIndustryFinancials                           1.577e+01  1.546e+01   1.020\nIndustryFood industry                       -1.632e+01  2.493e+01  -0.655\nIndustryFood processing                     -3.011e+00  2.034e+01  -0.148\nIndustryFood service                         2.150e+00  2.491e+01   0.086\nIndustryHealth                              -4.075e+00  2.492e+01  -0.164\nIndustryHealth insurance                     2.317e+00  2.035e+01   0.114\nIndustryHealthcare                           4.084e-01  1.661e+01   0.025\nIndustryInfotech                            -1.643e+01  2.493e+01  -0.659\nIndustryInsurance                           -1.076e+00  1.705e+01  -0.063\nIndustryMachinery                            3.445e+00  2.490e+01   0.138\nIndustryMedia                               -2.487e+00  2.491e+01  -0.100\nIndustryPetroleum industry                  -2.602e+01  1.595e+01  -1.631\nIndustryPharmaceutical industry             -1.666e+01  1.660e+01  -1.003\nIndustryPharmacy wholesale                   1.054e+00  2.492e+01   0.042\nIndustryRetail                              -1.174e+01  1.617e+01  -0.726\nIndustryRetail and cloud computing          -7.846e+00  2.919e+01  -0.269\nIndustryTechnology                           1.032e+01  1.661e+01   0.621\nIndustryTechnology and cloud computing      -1.047e+01  1.858e+01  -0.564\nIndustryTelecom hardware manufacturing       1.453e+00  2.491e+01   0.058\nIndustryTelecommunications                  -9.785e+00  1.856e+01  -0.527\nIndustryTransportation                      -1.802e+01  2.054e+01  -0.877\n                                            Pr(>|t|)  \n(Intercept)                                   0.5579  \nemployees                                     0.5079  \nIndustryAgriculture cooperative               0.5986  \nIndustryAgriculture manufacturing             0.7684  \nIndustryAirline                               0.8017  \nIndustryApparel                               0.9853  \nIndustryAutomotive and energy                 0.7117  \nIndustryAutomotive industry                   0.9696  \nIndustryBeverage                              0.8511  \nIndustryChemical industry                     0.2275  \nIndustryConglomerate                          0.7416  \nIndustryConglomerate and telecommunications   0.7421  \nIndustryConsumer products manufacturing       0.7793  \nIndustryElectronics industry                  0.6172  \nIndustryEnergy trading                        0.2701  \nIndustryFinancial                             0.8176  \nIndustryFinancial services                    0.0836 .\nIndustryFinancials                            0.3118  \nIndustryFood industry                         0.5150  \nIndustryFood processing                       0.8828  \nIndustryFood service                          0.9315  \nIndustryHealth                                0.8706  \nIndustryHealth insurance                      0.9097  \nIndustryHealthcare                            0.9805  \nIndustryInfotech                              0.5124  \nIndustryInsurance                             0.9499  \nIndustryMachinery                             0.8904  \nIndustryMedia                                 0.9208  \nIndustryPetroleum industry                    0.1080  \nIndustryPharmaceutical industry               0.3196  \nIndustryPharmacy wholesale                    0.9664  \nIndustryRetail                                0.4705  \nIndustryRetail and cloud computing            0.7890  \nIndustryTechnology                            0.5366  \nIndustryTechnology and cloud computing        0.5751  \nIndustryTelecom hardware manufacturing        0.9537  \nIndustryTelecommunications                    0.5999  \nIndustryTransportation                        0.3837  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 20.33 on 62 degrees of freedom\nMultiple R-squared:  0.4144,\tAdjusted R-squared:  0.06488 \nF-statistic: 1.186 on 37 and 62 DF,  p-value: 0.2725\n```\n\n\n:::\n:::\n\nBased on the multiple regression analysis, the model explores the impact of the number of employees and industry type on revenue growth. The results indicate that neither employees nor most industry types have statistically significant effects on revenue growth, as their p-values are generally greater than 0.05. The overall model explains about 41% of the variability in revenue growth (Multiple R-squared = 0.4144), but the adjusted R-squared (0.06488) suggests that the model's explanatory power diminishes when accounting for the number of predictors. This indicates that other factors may play a more substantial role in driving revenue growth among companies.\n\n------------------------------------------------------------------------\n\n### **Data Visualisation**\n\nI’ll use a bar plot to compare average revenue growth across different industries, highlighting which sectors experience the fastest growth.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a bar plot of average revenue growth by industry\navg_growth_by_industry <- companies %>%\n  group_by(Industry) %>%\n  summarize(avg_growth = mean(revenue_growth, na.rm = TRUE))\n\nggplot(avg_growth_by_industry, aes(x = reorder(Industry, avg_growth), y = avg_growth)) +\n  geom_bar(stat = \"identity\", fill = \"skyblue\") +\n  coord_flip() +\n  labs(\n    title = \"Average Revenue Growth by Industry\",\n    x = \"Industry\",\n    y = \"Average Revenue Growth (%)\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nThis graph shows the average revenue growth by industry, providing valuable insights into how different sectors perform financially. Industries such as Financial Services, Financials, and Technology demonstrate the highest average revenue growth rates, indicating strong expansion and market potential. Conversely, industries like Chemical Industry, Energy Trading, and Petroleum Industry show negative average revenue growth, highlighting potential challenges or downturns in these sectors. This visualization underscores the variability in revenue growth across industries, reflecting the influence of market trends, demand, and economic conditions on sector performance.\n\n------------------------------------------------------------------------\n\n### **Conclusion**\n\nIn this analysis, we explored the factors influencing revenue growth among the world’s top companies. A regression model revealed that neither the number of employees nor most industries had a statistically significant impact on growth, suggesting other factors may play a more substantial role. However, a closer look at industries highlighted significant variability, with Financial Services and Technology leading in average revenue growth, while sectors like Chemical Industry and Petroleum Industry faced declines. These findings emphasize the complexity of revenue growth dynamics, driven by a combination of sector-specific trends and broader economic forces. Future analyses could integrate additional variables, such as regional factors or market share, to deepen insights into company performance.\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}